common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as main_views


urlpatterns = [
    path('main/', main_views.index, name="index"),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

app_name = "users"
urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
]

common/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "main/index.html")

users/views.py
from django.shortcuts import render

# Create your views here.

common/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <!-- login fail reason page start -->
        {% include "form_errors.html" %}
        <!-- login fail reason page end -->
        <div class="mb-3">
            <label for="username">User</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">login</button>
    </form>
</div>
{% endblock %}

common/templates/from_errors.html
<!-- print field error and non-field error -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- field error -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- nonfield error -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>

common/templates/navbar.html
<!-- Navigation Bar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class='navbar-brand' href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls='navbarSupportedContent'
                aria-expanded="false"
                aria-label='Toggle navigation'>
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <!-- login page link start -->
                    <a class="nav-link" href="{% url 'common:login' %}">login</a>
                    <!-- login page link end -->
                </li>
            </ul>
        </div>
    </div>
</nav>

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>SW Holdings Daily Stock Summary</h1>
    <table border="1">
        <th>table1</th>
        <th>table2</th>
        <tr><!-- first table start -->
            <td>first space</td>
            <td>second space</td>
        </tr><!-- first table end -->
        <tr><!-- second table start -->
            <td>first space</td>
            <td>second space</td>
        </tr>
    </table>
</body>
</html>

mysite/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <!-- login fail reason page start -->
        {% include "form_errors.html" %}
        <!-- login fail reason page end -->
        <div class="mb-3">
            <label for="username">User</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">login</button>
    </form>
</div>
{% endblock %}

mysite/templates/from_errors.html
<!-- print field error and non-field error -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- field error -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- nonfield error -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>

mysite/templates/navbar.html
<!-- Navigation Bar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class='navbar-brand' href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls='navbarSupportedContent'
                aria-expanded="false"
                aria-label='Toggle navigation'>
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <!-- login page link start -->
                    <a class="nav-link" href="{% url 'common:login' %}">login</a>
                    <!-- login page link end -->
                </li>
            </ul>
        </div>
    </div>
</nav>

users/templates/users/login.html
<!-- users>login.html -->
{% block content %}

<h1>This is SW Holding Page.</h1>
<h3>Please Login. If you have no ID, please send me e-mail hugh17595@gmail.com </h3>
<h2>LOGIN PAGE</h2>
<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    <div>
        <label>User ID</label>
        <input type="text" name="username" id="username">
    </div>
    <div>
        <label>User Password</label>
        <input type="text" name="password" id="password">
    </div>
    <button type="submit">Login</button>
</form>

{% endblock %}